<?php
/**
 * Inchoo is not affiliated with or in any way responsible for this code.
 *
 * Commercial support is available directly from the [extension author](http://www.techytalk.info/contact/).
 *
 * @category Marko-M
 * @package SocialConnect
 * @author Marko Martinović <marko@techytalk.info>
 * @copyright Copyright (c) Marko Martinović (http://www.techytalk.info)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<div class="inchoo-socialconnect-login">
	<div class="<?php echo $this->_getColSet(); ?> inchoo-socialconnect-login-lower">
		<?php if($this->_googleEnabled()): ?>
			<?php echo $this->getChildHtml('inchoo_socialconnect_google_login_button'); ?>
		<?php endif; ?>
		<?php if($this->_facebookEnabled()): ?>
			<?php echo $this->getChildHtml('inchoo_socialconnect_facebook_login_button'); ?>
		<?php endif; ?>
		<?php if($this->_twitterEnabled()): ?>
			<?php echo $this->getChildHtml('inchoo_socialconnect_twitter_login_button'); ?>
		<?php endif; ?>
		<?php if($this->_linkedinEnabled()): ?>
			<?php echo $this->getChildHtml('inchoo_socialconnect_linkedin_login_button'); ?>
		<?php endif; ?>            
	</div>
</div>
